.PHONY:

run:
	# Corriendo Analizador de Gramáticas ;)
	python3 grammar_analyser.py

install:
	pip3 install PyQt5
	pip3 install pydot

clean:
	rm -rf cmp/__pycache__
	rm -rf testing/__pycache__
	rm -rf uis/__pycache__

test:
	# Ejecutando en consola :)
	python3 tester.py
